### ISSUE TITLE
(Grackle::TwitterError) "Unable to decode response: 745: unexpected token at

### ISSUE THREAD

**Issue by anitabharambe** [hayesdavis/grackle#17]
Hi,
I am getting "(Grackle::TwitterError) "Unable to decode response: 745: unexpected token at ... "  exception when i try to fetch the data from my twitter account. In the response, it is shown as an overcapacity exception.
Please let me know how to resolve this.

**Comment by hayesdavis** [comment]
That was the result of an error coming from Twitter. This is what a "fail whale" looks like. You'll need to handle these kinds of errors and retry as necessary.

**Comment by edEssential** [comment]
This didn't work for me... still getting the same error at command line.

private
  def self.client
    Grackle::Client.new(:auth=>{
      :type=>:oauth,
      :ssl=>true,
      :consumer_key=>'MY_CONSUMER_KEY',
      :consumer_secret=>'MY_CONSUMER_SECRET',
      :token=>"MY_TOKEN",
      :token_secret=>"MY_TOKEN_SECRET"
    })

  end

Any ideas?
