### ISSUE TITLE
Passing in `id` param to a query puts it in the URL rather than as actual param.

### ISSUE THREAD

**Issue by messick** [hayesdavis/grackle#30]
The `oembed` part of the 1.1 Twitter API can take param named `id`.  If it's passed in, then it becomes part of the URL like so:

```
21] pry(main)> client.statuses.oembed.json? maxwidth: 500, id: "337793757426614272"
Grackle::TwitterError: get http://api.twitter.com/1.1/statuses/oembed/337793757426614272.json?maxwidth=500 => 404: {"errors":[{"message":"Sorry, that page does not exist"...
```

**Comment by hayesdavis** [comment]
There's actually a flag you can pass into the Grackle::Client constructor called :auto_append_ids. Set this to false and it won't automatically insert the id like that. Sorry for the lack of documentation.

See here: https://github.com/hayesdavis/grackle/blob/master/lib/grackle/client.rb#L145
