### ISSUE TITLE
Unable to decode response: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by mmahalwy** [hayesdavis/grackle#35]
All of a sudden keep getting this error:

Unable to decode response: A JSON text must at least contain two octets!

Don't know why?

**Comment by canujohann** [comment]
Same problem for 3 days.. and I found this : http://www.zdnet.com/twitter-enforces-ssl-encryption-for-apps-connecting-to-its-api-7000025138/  According to the readme file, you can set ssl to true as parameter...

**Comment by hayesdavis** [comment]
@mmahalwy, @canujohann is correct. Twitter recently made the change to require SSL on all connections. Grackle defaults to ssl off (which I need to change soon) but you can turn it on by passing :ssl=>true in the constructor hash.

**Comment by edEssential** [comment]
private
  def self.client
    Grackle::Client.new(:auth=>{
      :type=>:oauth,
      :ssl=>true,
      :consumer_key=>'MY_CONSUMER_KEY',
      :consumer_secret=>'MY_CONSUMER_SECRET',
      :token=>"MY_TOKEN",
      :token_secret=>"MY_SECRET_TOKEN"
    })

  end

Still giving the same message at command line... any ideas?

**Comment by mmahalwy** [comment]
private
def self.client
Grackle::Client.new(:ssl=>true, :auth=>{

:type=>:oauth,
:consumer_key=>'MY_CONSUMER_KEY',
:consumer_secret=>'MY_CONSUMER_SECRET',
:token=>"MY_TOKEN",
:token_secret=>"MY_SECRET_TOKEN"
})

end

On Wed, Feb 12, 2014 at 5:57 AM, edEssential notifications@github.comwrote:

> private
> def self.client
> Grackle::Client.new(:auth=>{
> :type=>:oauth,
> :ssl=>true,
> :consumer_key=>'MY_CONSUMER_KEY',
> :consumer_secret=>'MY_CONSUMER_SECRET',
> :token=>"MY_TOKEN",
> :token_secret=>"MY_SECRET_TOKEN"
> })
> 
> end
> 
> Still giving the same message at command line... any ideas?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/hayesdavis/grackle/issues/35#issuecomment-34858177
> .

## 

_Mohamed El Mahallawy_

_@mmahalwy4167101981_

**Comment by hayesdavis** [comment]
@edEssential , @mmahalwy is correct. Looks like your :ssl parameter is inside your :auth hash. It needs to be specified outside of the :auth hash. After that, all should be well.

**Comment by mmahalwy** [comment]
@hayesdavis should have explain afterwards. Thanks!

**Comment by edEssential** [comment]
@mmahalwy @hayesdavis Works perfectly. Cheers!
